name: Auto update Julia dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every week
  push:
    branches:
      - main
    paths:
      - .github/workflows/update-manifest.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-manifest:
    permissions:
      contents: write
      pull-requests: write
    env:
      IMG_NAME: 'app:test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Build and load docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: 'env.Dockerfile'
          tags: ${{ env.IMG_NAME }}
          load: true
          target: base
      - name: Update Julia dependencies
        run: >
          docker run --rm -e JULIA_PKG_PRECOMPILE_AUTO=0
          -w /tmp -v ${{ github.workspace }}:/tmp
          ${{ env.IMG_NAME }}
          julia --color=yes --project=@. -e 'import Pkg; Pkg.update()'
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Julia update
          labels: |
            automerge
