name: Auto update Julia dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every week
  push:
    branches:
      - main
    paths:
      - .github/workflows/update-manifest.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VER: '3.x'
  APP_ID: '189113' # https://github.com/apps/wen-wei-s-pr-bot
  JULIA_NUM_THREADS: 'auto'
  JULIA_CONDAPKG_BACKEND: 'Null'
  JULIA_PKG_PRECOMPILE_AUTO: '0'

jobs:
  update-manifest:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VER }}
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
      - name: Update Julia dependencies
        env:
          PYTHON: ${{ env.pythonLocation }}/python
          JULIA_PYTHONCALL_EXE: ${{ env.pythonLocation }}/python
        run: julia --color=yes --project=@. -e "import Pkg; Pkg.update()"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
      - name: Automerge
        run: gh pr merge --merge --auto ${{ steps.cpr.outputs.pull-request-number }}
